owncloud:
  container_name: owncloud
  image: owncloud
  restart: always
  environment:
    - PUID=1000
    - PGID=1000
  ports:
      - 8084:80
  volumes:
    - /media/externalhd/owncloud/data:/var/www/html
    - /media/externalhd/owncloud/apps:/var/www/html/apps
    - /media/externalhd/owncloud/config:/var/www/html/config
    - /media/externalhd/owncloud/data/data:/var/www/html/data

postgres:
  container_name: postgresserver
  image: postgres:9.6
  volumes:
  - /media/externalhd/postgres/data:/var/lib/postgresql/data
  environment:
  - POSTGRES_USER=sa
  - POSTGRES_PASSWORD=Ibanez135135..
